#!/usr/bin/env bash

echo -e '\nStep: Linting ...'
npm run lint > /dev/null
echo -e '... Done\n'

echo -e '\nStep: Bundling ...'
npm run build || \
    {
        echo 'Bundling failed. Commit aborted'
        exit 1
    }
echo -e '... Done\n'

echo -e '\nStep: Staging modified files ...'
git add .
echo -e '... Done\n'
