# Brief: This workflow initializes the upstream repository by pushing the type commits

name: Init

on:
  workflow_dispatch: # Enables manual triggering
  push:
    branches: [main] # To trigger on repo creation from template

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:

  init:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out current (i.e. triggering) branch
        uses: actions/checkout@v4
      - name: Set up Node runtime
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: false
          cache: npm
      - name: Install dependencies
        run: npm ci # Clean, frozen install. Doesn't modify package.json or package-lock.json
      - name: Clean prior init, if any
        continue-on-error: true
        run: git ls-remote --tags origin kv/types/* | cut -f2 | xargs git push --delete origin
      - name: Init
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: src/init.js "${GITHUB_REPOSITORY}"
