name: Test

on:
  workflow_dispatch: # Enables manual triggering
  push:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:

  test:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out current (i.e. triggering) branch
        uses: actions/checkout@v4
      - name: Set up Node runtime
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: false
          cache: npm
      - name: Install dependencies
        run: npm ci # Clean, frozen install. Doesn't modify package.json or package-lock.json
      - name: Run tests
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PASSWORD: passwd
        run: npm test
